### ISSUE TITLE
Image & status attributes not showing correctly

### ISSUE THREAD

**Issue by jimbob1001** [ludeeus/custom_component_hadockermon#5]
Hi, nice work on this custom component! 

I can't seem to figure out why I am not getting the `status` &  `image` attributes to show up. Instead it says `false` &  `mdi:docker`

![screenshot_20180428-154943_01](https://user-images.githubusercontent.com/10485852/39397787-c6f22374-4afc-11e8-9d4e-10d896150d3f.jpg)

**Comment by ludeeus** [comment]
@jimbob1001 I'm getting the same thing, will investigate

**Comment by ludeeus** [comment]
This is fixed in version 1.2.0
Thanks for reporting
https://github.com/ludeeus/custom_component_hadockermon/releases/tag/1.2.0

**Comment by ludeeus** [comment]
Sorry about that.
Should be resolved in:
https://github.com/ludeeus/custom_component_hadockermon/releases/tag/1.2.1

**Comment by jimbob1001** [comment]
👍
